#!/usr/bin/env python3
"""
plot_hdf5_voltage_current.py
----------------------------
Plot voltage traces stored in the HDF5 files produced by simulate_and_store.py
and overlay the stimulus current used for the simulation.

Notes
-----
- The HDF5 files generated by simulate_and_store.py store voltage traces, but
  not the stimulus current itself.
- This script therefore reads the stimulus current from the original
  STIM_FILE recorded in the HDF5 metadata.
- If a future HDF5 file also stores a current dataset, this script will use it
  automatically.

Output
------
- A PDF with one page per probe, containing:
    * voltage trace in mV
    * stimulus current below it in a separate subplot
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Plot voltage traces and stimulus current from a BBP HDF5 file.'
    )
    parser.add_argument('--hdf5_file', help='Input HDF5 file from simulate_and_store.py')
    parser.add_argument(
        '-o', '--output', default=None,
        help='Output PDF path. Default: <hdf5 stem>_voltage_current.pdf'
    )
    parser.add_argument(
        '--probe', type=int, default=None,
        help='Plot only one probe index (0-based).'
    )
    parser.add_argument(
        '--max-probes', type=int, default=None,
        help='Maximum number of probes to plot.'
    )
    parser.add_argument(
        '--current-scale', type=float, default=1.0,
        help='Scale factor applied to the plotted stimulus current.'
    )
    return parser.parse_args()


def _decode_meta(meta_attr) -> dict:
    if meta_attr is None:
        return {}
    if isinstance(meta_attr, bytes):
        meta_attr = meta_attr.decode('utf-8')
    if isinstance(meta_attr, str):
        try:
            return json.loads(meta_attr)
        except json.JSONDecodeError:
            return {}
    return {}


def _load_stimulus_current(stim_file: str | None) -> np.ndarray | None:
    if not stim_file or not os.path.exists(stim_file):
        return None

    stim = np.genfromtxt(stim_file, dtype=np.float32)
    if stim.size == 0:
        return None

    # Make sure the returned stimulus is always 1D.
    if stim.ndim == 0:
        stim = np.array([float(stim)], dtype=np.float32)
    elif stim.ndim > 1:
        # Prefer the first column; if this is a single-row matrix, flatten it.
        stim = stim[:, 0] if stim.shape[0] > stim.shape[1] else stim[0, :]

    return np.asarray(stim, dtype=np.float32)


def _find_probe_groups(hf: h5py.File) -> list[str]:
    probe_keys = [k for k in hf.keys() if k.startswith('probe_')]
    probe_keys.sort(key=lambda x: int(x.split('_')[1]))
    return probe_keys


def _read_voltage_and_current(hf: h5py.File, probe_key: str, meta: dict,
                              current_scale: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    grp = hf[probe_key]
    volts = np.asarray(grp['volts'], dtype=np.float32)

    # Use current stored in HDF5 if present; otherwise load original stim file.
    current = None
    if 'current' in grp:
        current = np.asarray(grp['current'], dtype=np.float32)
    elif 'stim_current' in grp:
        current = np.asarray(grp['stim_current'], dtype=np.float32)
    else:
        current = _load_stimulus_current(meta.get('stim_file'))

    dt = float(meta.get('dt', 1.0))
    stim_skip = int(meta.get('stim_skip', 0))

    t_volt = (stim_skip + np.arange(len(volts), dtype=np.float32)) * dt

    if current is None:
        t_curr = t_volt.copy()
        current = np.zeros_like(volts, dtype=np.float32)
    else:
        current = np.asarray(current, dtype=np.float32)
        t_curr = np.arange(len(current), dtype=np.float32) * dt

    return t_volt, volts, t_curr, current * current_scale


def plot_hdf5_file(hdf5_path: str, output_pdf: str, probe_index: int | None,
                   max_probes: int | None, current_scale: float) -> None:
    with h5py.File(hdf5_path, 'r') as hf:
        meta = _decode_meta(hf.attrs.get('meta', None))
        probe_keys = _find_probe_groups(hf)

        if probe_index is not None:
            probe_keys = [k for k in probe_keys if int(k.split('_')[1]) == probe_index]

        if max_probes is not None:
            probe_keys = probe_keys[:max_probes]

        if not probe_keys:
            raise RuntimeError('No probe groups found to plot.')

        with PdfPages(output_pdf) as pdf:
            for probe_key in probe_keys:
                grp = hf[probe_key]
                label = grp.attrs.get('label', probe_key)

                t_volt, volts, t_curr, current = _read_voltage_and_current(
                    hf, probe_key, meta, current_scale
                )

                fig, (ax1, ax2) = plt.subplots(
                    2, 1, figsize=(14, 7), sharex=True,
                    gridspec_kw={'height_ratios': [2.2, 1.0], 'hspace': 0.08}
                )

                ax1.plot(t_volt, volts, color='navy', lw=1.0, label='Voltage (mV)')
                ax2.plot(t_curr, current, color='crimson', lw=0.7, alpha=0.85,
                         label='Stimulus current')

                ax1.set_ylabel('Voltage (mV)', color='navy')
                ax2.set_xlabel('Time (ms)')
                ax2.set_ylabel('Current', color='crimson')
                ax1.tick_params(axis='y', colors='navy')
                ax2.tick_params(axis='y', colors='crimson')
                ax1.tick_params(axis='x', labelbottom=False)
                ax1.grid(True, alpha=0.25)
                ax2.grid(True, alpha=0.25)

                title_parts = [os.path.basename(hdf5_path), str(label)]
                if meta.get('mType') and meta.get('eType') is not None:
                    title_parts.append(f"{meta.get('mType')}_{meta.get('eType')}_{meta.get('iType', '')}")
                ax1.set_title(' | '.join(title_parts), fontsize=12, fontweight='bold')

                ax1.legend(loc='upper right')
                ax2.legend(loc='upper right')

                if meta.get('stim_skip') is not None:
                    x_skip = float(meta['stim_skip']) * float(meta.get('dt', 1.0))
                    ax1.axvline(x_skip, color='gray', ls='--', lw=0.8, alpha=0.7)
                    ax2.axvline(x_skip, color='gray', ls='--', lw=0.8, alpha=0.7)

                plt.tight_layout()
                pdf.savefig(fig)
                plt.close(fig)

    print(f'Saved: {output_pdf}')


def main() -> None:
    args = parse_args()
    hdf5_path = os.path.abspath(args.hdf5_file)
    if not os.path.exists(hdf5_path):
        raise FileNotFoundError(hdf5_path)

    output_pdf = args.output
    if output_pdf is None:
        output_pdf = str(Path(hdf5_path).with_suffix('')) + '_voltage_current.pdf'

    plot_hdf5_file(
        hdf5_path=hdf5_path,
        output_pdf=output_pdf,
        probe_index=args.probe,
        max_probes=args.max_probes,
        current_scale=args.current_scale,
    )


if __name__ == '__main__':
    main()
