#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/usr/local/lib/python3.8/dist-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/usr/local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/pscratch/sd/k/ktub1999/main/DL4neurons2/Neuron_Model_HH/x86_64/.libs/libnrnmech.so" "$@"
